# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/FPGA/FPGA/TP/TP1part2/TP1part2.srcs/sources_1/bd/TP2/ip/TP2_ilmb_v10_0/TP2_ilmb_v10_0.xci
# IP: The module: 'TP2_ilmb_v10_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/FPGA/FPGA/TP/TP1part2/TP1part2.gen/sources_1/bd/TP2/ip/TP2_ilmb_v10_0/TP2_ilmb_v10_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'TP2_ilmb_v10_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: d:/FPGA/FPGA/TP/TP1part2/TP1part2.srcs/sources_1/bd/TP2/ip/TP2_ilmb_v10_0/TP2_ilmb_v10_0.xci
# IP: The module: 'TP2_ilmb_v10_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/FPGA/FPGA/TP/TP1part2/TP1part2.gen/sources_1/bd/TP2/ip/TP2_ilmb_v10_0/TP2_ilmb_v10_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'TP2_ilmb_v10_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
